### ISSUE TITLE
Conversion to CIELAB doesn't match other converters

### ISSUE THREAD

**Issue by korggy** [tompazourek/Colourful#34]
Maybe I'm doing something wrong, but when I try a basic RGB -> Lab conversion I'm getting a different answer than other converters out there.

`var c1 = Color.FromArgb(0, 255, 0);`
`var c2 = new RGBColor(c1);`
`var converter = new ColourfulConverter();`
`var c4 = converter.ToLab(c2);`

This gives me Lab [L=87.82, a=-79.29, b=80.99]

But when I try the same conversion on [http://colormine.org/convert/rgb-to-lab](url) I get: L = 87.74, a = -86.18, b = 83.18.

Any idea what I'm doing wrong here?

Thanks,
Mike

**Comment by tompazourek** [comment]
Hi @korggy, thanks for reaching out.

I'd guess that colormine values are wrong.

My process is for the conversion you specified following:

- I assume that the RGB working space is `sRGB` (this can be changed in `RGBColor` constructor), which is the most commonly used
- I convert it to linear RGB using the inverse companding process defined in the working space - for sRGB I use the process described [here][http://www.brucelindbloom.com/index.html?Eqn_XYZ_to_RGB.html].
- After I got RGB with linear channels, I convert it to XYZ using a conversion matrix that is constructed from the chromaticity primaries of the sRGB color space, the result will be an XYZ color with reference white point D65 (because sRGB has reference white point D65)
- Then I need to do convert XYZ to LAB color space. But when we talk about LAB color space, we usually mean LAB color space with reference white point D50 (Photoshop uses it as well), so a chromatic adaptation from D65 to D50 needs to be performed
- For the chromatic adaptation, I use the standard Von Kries chromatic adaptation that transforms the colors to LMS color space inside, and I am using Bradford LMS transform matrix (also used in CMCCAT97) for that
- After the chromatic adaptation, I have a XYZ color with reference to D50, which I can convert to LAB using [this method](http://www.brucelindbloom.com/index.html?Eqn_XYZ_to_Lab.html)

This whole process in Colourful is designed based on the information I collected from [Bruce Lindbloom's website](http://www.brucelindbloom.com/) with some of my research on the topic.

I tested my values with this calculator: http://www.brucelindbloom.com/index.html?ColorCalculator.html and the **values match**. Try entering 0, 1, 0 to RGB, the default settings of that calculator should be the same as default settings of `ColourfulConverter` class, then the LAB coefficients should match the ones generated by Colourful.

For a second test, try [Wolfram Alpha](http://www.wolframalpha.com/input/?dataset=&i=RGB+0,+255,+0+to+LAB), their values also agree with mine.

**Comment by tompazourek** [comment]
Closing this now. Feel free to reopen for a follow-up.
