### ISSUE TITLE
getting stackoverflow exception in Colourful 2.0 using F#

### ISSUE THREAD

**Issue by yuyoyuppe** [tompazourek/Colourful#44]
```fsharp
      let rgb = Colourful.RGBColor systemColor 
      let cnvrtr = Colourful.Conversion.ColourfulConverter()
      let lab = cnvrtr.ToLab rgb
```
same code works fine with v1.2.2

**Comment by tompazourek** [comment]
Thanks for the report. Can you please provide the value of `systemColor`?

**Comment by yuyoyuppe** [comment]
```43 40 34```
and resulting `rgb`:
```
rgb
{RGB [R=0.17, G=0.16, B=0.13]}
    B: 0.13333333333333333
    G: 0.15686274509803921
    R: 0.16862745098039217
    Vector: {double[3]}
    WorkingSpace: {Colourful.Implementation.RGB.RGBWorkingSpace}
```
but I don't think that's important, because I'm getting this exception with basically any input.

**Comment by w29ahmed** [comment]
Seeing the same issue in C#, trying to convert LinearRGBColor to any other colour space with the default setup for the ColourfulConverter

**Comment by tompazourek** [comment]
Sorry, but I'm still not able to reproduce this.

**Could either of you please provide a code sample with all the values so that I can reproduce the exception?**

---

This is what I get when trying values from @yuyoyuppe (note I'm in C#, not F#):

![yuyoyuppe](https://user-images.githubusercontent.com/370699/48015674-f5e2f280-e129-11e8-9e58-b463f9018c65.PNG)

---

This is what I get when converting sample LinearRGBColor to Lab colour space with the default setup for the ColourfulConverter (reported by @w29ahmed):

![w29ahmed](https://user-images.githubusercontent.com/370699/48015723-157a1b00-e12a-11e8-9ef5-355446733f2b.PNG)

---

**Comment by w29ahmed** [comment]
The issue on my end had something to do with Visual Studio 2015, it worked fine on Visual Studio 2017. Note you actually can't open the solution on Visual Studio 2015, I was referencing the generated .dll directly in there, but seems to work fine in Visual Studio 2017, both through linking the .dll or building manually. Not totally sure what the problem could be with VS 2015.

**Comment by tompazourek** [comment]
@w29ahmed It's possible that the solution cannot be opened in VS2015. After all, it's a .NET Standard class library project, and it uses some of the new features from the current versions of C#. Those might not be fully supported in VS2015.

But you shouldn't need to open the solution at all. You can just use the NuGet package, and that one will work wherever you can run .NET Framework 4.5 or .NET Standard 1.1.
