### ISSUE TITLE
Converting RGB to xyY - strange Luminance value?

### ISSUE THREAD

**Issue by RotesWasser** [tompazourek/Colourful#79]
Hi there,

I'm using your library to convert colors for use with Philips Hue lights, but there's something weird happening / something I don't quite understand. When converting a fully bright blue `LinearRGBColor` to xyY, the resulting `Luminance` is not `1`.

```csharp
 var converter = new ColourfulConverter();
var fullBlue = new LinearRGBColor(0, 0, 1);

var converted = converter.ToxyY(fullBlue);
Console.WriteLine(converted.Luminance); // prints 0.07217499330655958
```

Am I misusing the library in some way, or is RGB just a bad origin color format as it muddies luminance and chromacity?

Thank you very much :)

**Comment by KelSolaar** [comment]
@RotesWasser: This is entirely expected, our visual system sensitivity to the electro-magnetic spectrum is not uniform but more like a gaussian curve peaking at green wavelength about 555nm. See the [luminous efficiency function](https://en.m.wikipedia.org/wiki/Luminosity_function) for more details.

The RGB model represents mixtures of R, G, B colours and because it does so in a way that is perceptual, it is weighted accordingly and Luminance peaks for green. The equation for the sRGB colourspace is as follows:

> L = 0.2126R + 0.7152G + 0.0722B

**Comment by RotesWasser** [comment]
Thanks for the super quick reply and explaination! 

The problem that I now face is how I should let users input colors for the lights, as the Lamp API seems to expect xy coordinates and a brightness value between 1 and 254. Following that formula does not allow the lamp to reach its peak brightness when set to blue.

Should I just let users pick the xy coordinates from a horseshoe diagram and have them specify brightness as a second parameter?

Alternatively, would HSV make more sense here as a origin color space?

**Comment by KelSolaar** [comment]
You could certainly use the RGB model to determine the CIE xy chromaticity coordinates and then either use a separate control for luminance OR hardcode it to peak depending what you a trying to achieve. It is however unlikely that the light itself will be able to produce the same luminous flux to a human observer because it would mean increasing the wattage/radiant flux tremendously to compensate for the HVS sensitivity.

**Comment by RotesWasser** [comment]
I will probably go for letting the users choose, I think this best suits my use case. Thanks for your quick reply and sorry for replying so late, I'm currently swamped with stuff :)
